In [5]:
# PythonでWeb上の画像などのファイルをダウンロード
# import os
# import pprint
# import time
import urllib.error
import urllib.request

def download_file(url, dst_path):
    try:
        with urllib.request.urlopen(url) as web_file:
            data = web_file.read()
            with open(dst_path, mode='wb') as local_file:
                local_file.write(data)
    except urllib.error.URLError as e:
        print(e)

url = 'https://www.jsps.go.jp/j-grantsinaid/27_kdata/data/3-4-1/3-4-1_r2.pdf'
# windowsではopenの引数にフォルダを指定するとPermissionErrorになる
dst_path = './data/test.pdf'
download_file(url, dst_path)

In [28]:
import pandas as pd
import camelot.io as camelot
#pdfファイルを読み込む
table = camelot.read_pdf("./data/test.pdf", pages='all', lattice=True, split_text=True, strip_text='\n')
lists = []  # 一時保存用リスト
for t in table:
  lists.append(t.df)
  df = pd.concat(lists)  # データフレームを結合

df
# 42.4s

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,機関名,新規＋継続,,,,,,,,,,,
1,,採択件数（件）,女性比率（％）,40歳未満比率（％）,直接経費（千円）,間接経費（千円）,合計（千円）,基盤研究の件数（件）,,,備考,,
2,,,,,,,,基盤研究Ａ,基盤研究B,基盤研究C,新規応募件数（件）,新規採択件数（件）,新規採択率（％）
3,東京大学＊,"4,202",15.9%,38.5%,"17,345,795","5,203,739","22,549,534",320,820,982,"3,864","1,511",39.1%
4,京都大学＊,"3,022",13.5%,31.1%,"10,716,850","3,215,055","13,931,905",180,656,826,"2,872","1,083",37.7%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,科学教育総合研究所株式会社（研究・開発部）,1,0.0%,0.0%,"1,100",330,"1,430",0,0,1,0,0,－
48,株式会社辻料理教育研究所（辻静雄料理教育研究所 研究部門）,1,100.0%,100.0%,"1,100",330,"1,430",0,0,0,2,1,50.0%
49,社会医療法人神鋼記念会（総合医学研究センター）,1,0.0%,0.0%,900,270,"1,170",0,0,0,1,0,0.0%
50,株式会社神戸工業試験場（生産本部技術開発部）,1,0.0%,100.0%,"1,000",300,"1,300",0,0,0,3,0,0.0%
51,株式会社膠原病研究所,1,0.0%,100.0%,"1,000",300,"1,300",0,0,1,1,0,0.0%

In [185]:
df2 = df
df2.columns = ["機関名","採択件数（件）","女性比率（％）","40歳未満比率（％）","直接経費（千円）","間接経費（千円）","合計（千円）","基盤研究Ａ","基盤研究B","基盤研究C","新規応募件数（件）","新規採択件数（件）","新規採択率（％）"]
# df[df['機関名']=="機関名"]
# df[df['機関名'].isnull()]
# print(df2[df2['機関名'] == ''])
# print(df2[df2['機関名'] == '機関名'])
# print(df2[(df2['機関名'] == '')|(df2['機関名'] == '機関名')])
# df2['機関名'].isnull()
df_and = df2[(df2['機関名'] == '機関名') | (df2['機関名'] == '')]
# df_and.index
df3 = df2.drop(df_and.index)
df3.reset_index(inplace=True, drop=True)
# ok df3['機関名'] = df3['機関名'].str.replace('＊', '')
df3.loc['機関名':,:] = df3.loc['機関名':,:].replace('＊', '')
df3

C:\Users\libso23-user\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
C:\Users\libso23-user\anaconda3\lib\site-packages\pandas\core\indexing.py:692: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

,機関名,採択件数（件）,女性比率（％）,40歳未満比率（％）,直接経費（千円）,間接経費（千円）,合計（千円）,基盤研究Ａ,基盤研究B,基盤研究C,新規応募件数（件）,新規採択件数（件）,新規採択率（％）
0,東京大学,"4,202",15.9%,38.5%,"17,345,795","5,203,739","22,549,534",320,820,982,"3,864","1,511",39.1%
1,京都大学,"3,022",13.5%,31.1%,"10,716,850","3,215,055","13,931,905",180,656,826,"2,872","1,083",37.7%
2,大阪大学,"2,665",16.4%,34.2%,"8,048,524","2,414,557","10,463,081",137,459,879,"2,907",969,33.3%
3,東北大学,"2,525",13.9%,35.0%,"7,497,750","2,249,325","9,747,075",147,472,789,"2,716",859,31.6%
4,九州大学,"1,943",16.0%,32.9%,"5,429,701","1,628,910","7,058,611",108,357,699,"2,361",693,29.4%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,科学教育総合研究所株式会社（研究・開発部）,1,0.0%,0.0%,"1,100",330,"1,430",0,0,1,0,0,－
1350,株式会社辻料理教育研究所（辻静雄料理教育研究所 研究部門）,1,100.0%,100.0%,"1,100",330,"1,430",0,0,0,2,1,50.0%
1351,社会医療法人神鋼記念会（総合医学研究センター）,1,0.0%,0.0%,900,270,"1,170",0,0,0,1,0,0.0%
1352,株式会社神戸工業試験場（生産本部技術開発部）,1,0.0%,100.0%,"1,000",300,"1,300",0,0,0,3,0,0.0%
1353,株式会社膠原病研究所,1,0.0%,100.0%,"1,000",300,"1,300",0,0,1,1,0,0.0%

In [176]:
# データフレーム内の文字列を抽出
col_list2 = ["女性比率（％）","40歳未満比率（％）","新規採択率（％）"]
for item in col_list2:
  tokutei = df3[item].str.contains('大分県立看護科学大学')
df3[tokutei]

Empty DataFrame
Columns: [機関名, 採択件数（件）, 女性比率（％）, 40歳未満比率（％）, 直接経費（千円）, 間接経費（千円）, 合計（千円）, 基盤研究Ａ, 基盤研究B, 基盤研究C, 新規応募件数（件）, 新規採択件数（件）, 新規採択率（％）]
Index: []

In [182]:
# print(df.dtypes)
# 数字に見える列を抽出
# print(df3.loc[:,["採択件数（件）","直接経費（千円）","間接経費（千円）","合計（千円）","基盤研究Ａ","基盤研究B","基盤研究C","新規応募件数（件）","新規採択件数（件）"]])
# ％つきの列を抽出
#print(df3.loc[:,["女性比率（％）","40歳未満比率（％）","新規採択率（％）"]])
# ｘｘｘdf3 = pd.to_numeric(df3.loc[:,
import numpy as np
col_list1 = ["採択件数（件）","直接経費（千円）","間接経費（千円）","合計（千円）","基盤研究Ａ","基盤研究B","基盤研究C","新規応募件数（件）","新規採択件数（件）"]
for item in col_list1:
    # if not df3[item].isnumeric(): # 'Series' object has no attribute 'isnumeric'
    # if type(df3[item]) is str:
    # ok df3[item] = pd.to_numeric(df3[item].astype(str).str.replace(',', ''), errors='coerce')
    # Try using .loc[row_indexer,col_indexer] = value instead
    # AttributeError: 'DataFrame' object has no attribute 'str'
    # df3.loc[item:,:] = pd.to_numeric(df3.loc[item:,:].astype(str).str.replace(',', ''), errors='coerce')
    df3[item] = df3[item].apply(lambda x: x.replace(',',''))
    # xx df3.loc[item:,:] = df3.loc[item:,:].apply(lambda x: x.replace(',',''))
col_list2 = ["女性比率（％）","40歳未満比率（％）","新規採択率（％）"]
for item in col_list2:
    df3[item] = pd.to_numeric(df3[item].astype(str).str.replace('%', ''), errors='coerce', downcast='float') * 0.01
    # ValueError: could not convert string to float: '－'
    # df3.loc[item:,:] = df3.loc[item:,:].apply(lambda x: x.replace('－','0'))
    # df3.loc[item:,:] = df3.loc[item:,:].apply(lambda x: x.replace('%','')).astype(float) * 0.01
    # df3[item] = df3[item].astype(float)   # .astype(int)
    
df3

<ipython-input-182-43c0e400ace3>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3[item] = df3[item].apply(lambda x: x.replace(',',''))
<ipython-input-182-43c0e400ace3>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3[item] = pd.to_numeric(df3[item].astype(str).str.replace('%', ''), errors='coerce', downcast='float') * 0.01

,機関名,採択件数（件）,女性比率（％）,40歳未満比率（％）,直接経費（千円）,間接経費（千円）,合計（千円）,基盤研究Ａ,基盤研究B,基盤研究C,新規応募件数（件）,新規採択件数（件）,新規採択率（％）
0,東京大学,4202,0.00159,0.00385,17345795,5203739,22549534,320,820,982,3864,1511,0.00391
1,京都大学,3022,0.00135,0.00311,10716850,3215055,13931905,180,656,826,2872,1083,0.00377
2,大阪大学,2665,0.00164,0.00342,8048524,2414557,10463081,137,459,879,2907,969,0.00333
3,東北大学,2525,0.00139,0.00350,7497750,2249325,9747075,147,472,789,2716,859,0.00316
4,九州大学,1943,0.00160,0.00329,5429701,1628910,7058611,108,357,699,2361,693,0.00294
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,科学教育総合研究所株式会社（研究・開発部）,1,0.00000,0.00000,1100,330,1430,0,0,1,0,0,NaN
1350,株式会社辻料理教育研究所（辻静雄料理教育研究所 研究部門）,1,0.01000,0.01000,1100,330,1430,0,0,0,2,1,0.00500
1351,社会医療法人神鋼記念会（総合医学研究センター）,1,0.00000,0.00000,900,270,1170,0,0,0,1,0,0.00000
1352,株式会社神戸工業試験場（生産本部技術開発部）,1,0.00000,0.01000,1000,300,1300,0,0,0,3,0,0.00000
1353,株式会社膠原病研究所,1,0.00000,0.01000,1000,300,1300,0,0,1,1,0,0.00000

In [124]:
df3

,機関名,採択件数（件）,女性比率（％）,40歳未満比率（％）,直接経費（千円）,間接経費（千円）,合計（千円）,基盤研究Ａ,基盤研究B,基盤研究C,新規応募件数（件）,新規採択件数（件）,新規採択率（％）
0,東京大学,4202,0.159,0.385,17345795,5203739,22549534,320,820,982,3864,1511,0.391
1,京都大学,3022,0.135,0.311,10716850,3215055,13931905,180,656,826,2872,1083,0.377
2,大阪大学,2665,0.164,0.342,8048524,2414557,10463081,137,459,879,2907,969,0.333
3,東北大学,2525,0.139,0.350,7497750,2249325,9747075,147,472,789,2716,859,0.316
4,九州大学,1943,0.160,0.329,5429701,1628910,7058611,108,357,699,2361,693,0.294
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,科学教育総合研究所株式会社（研究・開発部）,1,0.000,0.000,1100,330,1430,0,0,1,0,0,NaN
1350,株式会社辻料理教育研究所（辻静雄料理教育研究所 研究部門）,1,1.000,1.000,1100,330,1430,0,0,0,2,1,0.500
1351,社会医療法人神鋼記念会（総合医学研究センター）,1,0.000,0.000,900,270,1170,0,0,0,1,0,0.000
1352,株式会社神戸工業試験場（生産本部技術開発部）,1,0.000,1.000,1000,300,1300,0,0,0,3,0,0.000
1353,株式会社膠原病研究所,1,0.000,1.000,1000,300,1300,0,0,1,1,0,0.000

In [100]:
# excelファイルへ出力
with pd.ExcelWriter("./data/outFile.xlsx") as writer:
  df3.to_excel(writer, sheet_name='sheet1', index=True, header=True)